### ISSUE TITLE
switching versus fusion 

### ISSUE THREAD

**Issue by Qiang1991** [alistairewj/peak-detector#3]
The switching algorithm here is more complex than the fusion based algorithm,  which is suggested in Figure 3 of the paper "Multimodal heart beat detection using signal quality indices".  The switching gains better performance?

**Comment by alistairewj** [comment]
I'm not sure which algorithm you are referring to so I'll just describe both.

The SQI switching algorithm, implemented in `detect_sqi.m`, used estimates of signal quality on each individual lead to switch between them. The possible leads were ECG and ABP.

The regularity switching algorithm estimates the "regularity" of the RR intervals on each channel. The one with the lowest score, i.e. the most regular, is kept. This algorithm is in `detect_regularity.m`.

In the database we evaluated for the PhysioNet/CinC 2015 challenge, both methods performed equivalently. The SQI method will probably fare better during arrhythmia, though we have yet to test this.

Did that answer your question?

**Comment by Qiang1991** [comment]
Thank you for the answer.

By "fusion", I mean the FSQI approach you described in your paper "Multimodal heart beat detection using signal quality indices" in journal "Physiological measuremen" in 2015.

I wonder which one is better?

**Comment by alistairewj** [comment]
Right! FSQI is the SQI switching algorithm. In general, we prefer the FSQI algorithm, because it makes no assumptions about the regularity of the RR interval - assumptions which may be violated in the cases of arrhythmia (most notably AFIB). In the actual evaluation, the two methods performed equivalently.

**Comment by Qiang1991** [comment]
OK, since FSQI is the SQI switching algorithm, I will use it to determine whether to trust the different channels of signals, and use qrs_final in " detect_sqi.m" as the QRS position.

**Comment by alistairewj** [comment]
Sounds appropriate.
